/**
 * Created by oliverwang on 12/10/15.
 */
module.exports = {data: [{

    "_id": {"$oid": "5160756b96cc62079cc2db15"},
    "name": "Drop Biscuits and Sausage Gravy",
    "ingredients": "Biscuits\n3 cups All-purpose Flour\n2 Tablespoons Baking Powder\n1/2 teaspoon Salt\n1-1/2 stick (3/4 Cup) Cold Butter, Cut Into Pieces\n1-1/4 cup Butermilk\n SAUSAGE GRAVY\n1 pound Breakfast Sausage, Hot Or Mild\n1/3 cup All-purpose Flour\n4 cups Whole Milk\n1/2 teaspoon Seasoned Salt\n2 teaspoons Black Pepper, More To Taste",
    "url": "http://thepioneerwoman.com/cooking/2013/03/drop-biscuits-and-sausage-gravy/",
    "image": "http://static.thepioneerwoman.com/cooking/files/2013/03/bisgrav.jpg", "ts": {"$date": 1365276011104},
    "cookTime": "PT30M",
    "source": "thepioneerwoman",
    "recipeYield": "12",
    "datePublished": "2013-03-11",
    "prepTime": "PT10M",
    "description": "Late Saturday afternoon, after Marlboro Man had returned home with the soccer-playing girls, and I had returned home with the..."
},


{
    "_id": {"$oid": "5160756d96cc62079cc2db16"},
    "name": "Hot Roast Beef Sandwiches",
    "ingredients": "12 whole Dinner Rolls Or Small Sandwich Buns (I Used Whole Wheat)\n1 pound Thinly Shaved Roast Beef Or Ham (or Both!)\n1 pound Cheese (Provolone, Swiss, Mozzarella, Even Cheez Whiz!)\n1/4 cup Mayonnaise\n3 Tablespoons Grated Onion (or 1 Tbsp Dried Onion Flakes))\n1 Tablespoon Poppy Seeds\n1 Tablespoon Spicy Mustard\n1 Tablespoon Horseradish Mayo Or Straight Prepared Horseradish\n Dash Of Worcestershire\n Optional Dressing Ingredients: Sriracha, Hot Sauce, Dried Onion Flakes Instead Of Fresh, Garlic Powder, Pepper, Etc.)",
    "url": "http://thepioneerwoman.com/cooking/2013/03/hot-roast-beef-sandwiches/",
    "image": "http://static.thepioneerwoman.com/cooking/files/2013/03/sandwiches.jpg",
    "ts": {"$date": 1365276013902},
    "cookTime": "PT20M",
    "source": "thepioneerwoman",
    "recipeYield": "12",
    "datePublished": "2013-03-13",
    "prepTime": "PT20M",
    "description": "When I was growing up, I participated in my Episcopal church's youth group, and I have lots of memories of weekly meetings wh..."
},
{
    "_id": {"$oid": "5160756f96cc6207a37ff777"},
    "name": "Morrocan Carrot and Chickpea Salad",
    "ingredients": "Dressing:\n1 tablespoon cumin seeds\n1/3 cup / 80 ml extra virgin olive oil\n2 tablespoons fresh lemon juice\n1 tablespoon honey\n1/2 teaspoon fine sea salt, plus more to taste\n1/8 teaspoon cayenne pepper\n10 ounces carrots, shredded on a box grater or sliced whisper thin on a mandolin\n2 cups cooked chickpeas (or one 15- ounce can, drained and rinsed)\n2/3 cup / 100 g  dried pluots, plums, or dates cut into chickpea-sized pieces\n1/3 cup / 30 g fresh mint, torn\nFor serving: lots of toasted almond slices, dried or fresh rose petals - all optional (but great additions!)",
    "url": "http://www.101cookbooks.com/archives/moroccan-carrot-and-chickpea-salad-recipe.html",
    "image": "http://www.101cookbooks.com/mt-static/images/food/moroccan_carrot_salad_recipe.jpg",
    "ts": {"$date": 1365276015332},
    "datePublished": "2013-01-07",
    "source": "101cookbooks",
    "prepTime": "PT15M",
    "description": "A beauty of a carrot salad - tricked out with chickpeas, chunks of dried pluots, sliced almonds, and a toasted cumin dressing. Thank you Diane Morgan."
},
{
    "_id": {"$oid": "5160757096cc62079cc2db17"},
    "name": "Mixed Berry Shortcake",
    "ingredients": "Biscuits\n3 cups All-purpose Flour\n2 Tablespoons Baking Powder\n3 Tablespoons Sugar\n1/2 teaspoon Salt\n1-1/2 stick (3/4 Cup) Cold Butter, Cut Into Pieces\n1-1/4 cup Buttermilk\n1/2 teaspoon Almond Extract (optional)\n Berries\n2 pints Mixed Berries And/or Sliced Strawberries\n1/3 cup Sugar\n Zest And Juice Of 1 Small Orange\n SWEET YOGURT CREAM\n1 package (7 Ounces) Plain Greek Yogurt\n1 cup Cold Heavy Cream\n1/2 cup Sugar\n2 Tablespoons Brown Sugar",
    "url": "http://thepioneerwoman.com/cooking/2013/03/mixed-berry-shortcake/",
    "image": "http://static.thepioneerwoman.com/cooking/files/2013/03/shortcake.jpg",
    "ts": {"$date": 1365276016700},
    "cookTime": "PT15M",
    "source": "thepioneerwoman",
    "recipeYield": "8",
    "datePublished": "2013-03-18",
    "prepTime": "PT15M",
    "description": "It's Monday! It's a brand new week! The birds are chirping! The coffee's brewing! Everything has such hope and promise!     A..."
},
{
    "_id": {"$oid": "5160757496cc6207a37ff778"},
    "name": "Pomegranate Yogurt Bowl",
    "ingredients": "For each bowl: \na big dollop of Greek yogurt\n2 tablespoons fresh pomegranate juice\na drizzle of honey\na handful of puffed quinoa crisps (or other cereal/granola)\nsprinkling of toasted sunflower seeds\noptional: whole pomegranate seeds or fresh/dried rose petals, a bit of bee pollen",
    "url": "http://www.101cookbooks.com/archives/pomegranate-yogurt-bowl-recipe.html",
    "image": "http://www.101cookbooks.com/mt-static/images/food/breakfast_yogurt_bowl.jpg",
    "ts": {"$date": 1365276020318},
    "datePublished": "2013-01-20",
    "source": "101cookbooks",
    "recipeYield": "Serves 1.",
    "prepTime": "PT5M",
    "description": "A simple breakfast bowl made with Greek yogurt, fresh pomegranate juice, puffed quinoa cereal, toasted sunflower seeds, and honey."
},
{
    "_id": {"$oid": "5160757596cc62079cc2db18"},
    "name": "Krispy Easter Eggs",
    "ingredients": "4 Tablespoons Butter\n1 package (10 Ounces) Mini Marshmallows\n6 cups Rice Krispies\n Assorted Sprinkles\n Small Chocolate Easter Eggs\n Plastic Easter Eggs",
    "url": "http://thepioneerwoman.com/cooking/2013/03/krispy-easter-eggs/",
    "image": "http://static.thepioneerwoman.com/cooking/files/2013/03/DSC_9637.jpg",
    "ts": {"$date": 1365276021992},
    "cookTime": "PT5M",
    "source": "thepioneerwoman",
    "recipeYield": "12",
    "datePublished": "2013-03-25",
    "prepTime": "PT20M",
    "description": "Imagine the Easter Bunny laying an egg.     Wait. That’s not anatomically possible.     And anyway, the Easter Bunny is a b..."
},
{
    "_id": {"$oid": "5160757596cc6207aada322f"},
    "totalTime": "PT1H15M",
    "description": "Recently, there have been moments that catch me off my emotional guard. I'll be standing in my parents living room, thinking about my childhood/early adulth",
    "ingredients": "3-4 handfuls spinach\n½ cup kamut, uncooked\n¼ cup sunflower seeds\n2 ounces feta\n½ cup fresh squeezed orange juice (app. 2 oranges)\n¼ cup walnut oil\n2 tablespoons honey\n¼-1/2 teaspoon red chili flakes",
    "url": "http://naturallyella.com/2013/03/18/spinach-and-kamut-salad-with-chili-orange-dressing/",
    "image": "http://cdn.naturallyella.com/files/2013/03/IMG_6515-200x300.jpg",
    "creator": "Erin Alderson",
    "ts": {"$date": 1365276021873},
    "datePublished": "2013-03-18T07:36:07+00:00",
    "source": "naturallyella",
    "recipeYield": "2",
    "cookTime": "PT60M",
    "recipeCategory": "Salad",
    "prepTime": "PT15M",
    "name": "Spinach and Kamut Salad with Chili-Orange Dressing"
},
{
    "_id": {"$oid": "5160757696cc62079cc2db19"},
    "name": "Eggs in Hash Brown Nests",
    "ingredients": "6 whole Medium Russet Potatoes (6 To 8)\n Salt And Pepper, to taste\n24 whole Large Eggs\n Non-stick Cooking Spray",
    "url": "http://thepioneerwoman.com/cooking/2013/03/eggs-in-hash-brown-nests/",
    "image": "http://static.thepioneerwoman.com/cooking/files/2013/03/DSC_7863.jpg",
    "ts": {"$date": 1365276022867},
    "cookTime": "PT1H30M",
    "source": "thepioneerwoman",
    "recipeYield": "12",
    "datePublished": "2013-03-26",
    "prepTime": "PT15M",
    "description": "These are the perfect little side dish for Easter Brunch: Tender-but-crispy potato nests with a luscious baked egg in the mid..."
},
{
    "_id": {"$oid": "5160757696cc6207a37ff779"},
    "name": "Za'atar",
    "ingredients": "4 tablespoons fresh thyme leaves, stripped from stems (or equivalent dried)\n2  teaspoons ground sumac*\nscant 1/2 teaspoon fine sea salt, or to taste\n1 tablespoon toasted sesame seeds",
    "url": "http://www.101cookbooks.com/archives/zaatar-recipe.html",
    "image": "http://www.101cookbooks.com/mt-static/images/food/zaatar.jpg",
    "ts": {"$date": 1365276022231},
    "cookTime": "PT10M",
    "source": "101cookbooks",
    "datePublished": "2013-01-27",
    "prepTime": "PT5M",
    "description": "Za'atar is an incredibly versatile Middle Eastern spice blend, one of my favorites. Particularly this time of year when it's a welcome addition to all sorts of roasted vegetables, soups and stews, or simply sprinkled over everything from yogurt, to eggs, to savory granola."
}];
